rpnJason: rpn.cpp fraction.hpp linkedlist.hpp stack.hpp
	g++ -o rpnJason rpn.cpp

tar: rpn.cpp fraction.hpp linkedlist.hpp stack.hpp
	tar -cvf Jasonrpn\rpn.cpp fraction.hpp linkedlist.hpp stack.hpp 

clean:
	rm *.o